version: '3.8'
services:
  nest_server:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ./:/dump/app
    container_name: nest_server
    ports:
      - 8000:8000
    depends_on:
      - mysql_blog

  mysql_blog:
    platform: linux/x86_64
    image: mysql:latest
    environment:
      MYSQL_HOST: ${DB_HOST}
      MYSQL_DATABASE: ${DB_NAME}
      MYSQL_ROOT_PASSWORD: ${DB_PWD}
    container_name: mysql_blog
    ports:
      - 3306:3306
